#!/usr/bin/with-contenv bash

if [ ! -a /config/www/dcc.lock ]; then
  echo "**** Installing DCC  ****"
  rm -Rf /config/www/*
  git clone -b \
    gh-pages \
      https://github.com/Griefed/dcc-web.git \
        /config/www
  touch /config/www/dcc.lock
fi

# Permission Stuffs
chown -R \
  abc:abc \
    /config/www
